"""Dump both catalogues to static JSON for the frontend.

    python export_catalogue.py            # writes frontend/src/data/catalogue*.json
    python export_catalogue.py --check    # exits 1 if the files are out of date

Why this exists
---------------
The teaching content — the gate reference cards, the concepts, the circuit
index, and each circuit's gates plus its explain block — is the point of the
project, and all of it used to require a running backend. A statically built frontend served from anywhere
therefore lost it. This writes the same content the API serves into JSON the
frontend imports as a fallback, exactly as quantumEngine.js already stands in
for /api/simulate.

How it stays honest
-------------------
The routes are IMPORTED and CALLED, not reimplemented: `main.concepts`,
`main.circuits` and `main.circuit_detail` are the same functions FastAPI serves,
so what lands in the JSON is what the API would have returned, byte for byte
after serialisation. Nothing here reads the spec files directly except to
enumerate case ids.

The generated files are committed so that a checkout builds without Python, and
catalogue_drift_test.py fetches every one of these routes from a live uvicorn
and asserts the JSON still matches. Re-run this script whenever a spec file or
explain.py changes; never hand-edit the output.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).parent
DATA_DIR = HERE.parent / "frontend" / "src" / "data"

# Keep this in step with catalogue_drift_test.py, which reads the same files.
FILES = {1: DATA_DIR / "catalogue1q.json", 2: DATA_DIR / "catalogue2q.json"}

BANNER = ("GENERATED by backend/export_catalogue.py from circuits_spec*.json + "
          "explain*.py — do not edit by hand; re-run the script. "
          "catalogue_drift_test.py fails if this drifts from the live API.")


def build(qubits: int) -> dict:
    """Every catalogue route for one catalogue, in one document.

    Imported lazily so `--help` works without FastAPI installed.
    """
    import main

    cases = main._spec(qubits)["cases"]
    return {
        "_generated": BANNER,
        "qubits": qubits,
        # /api/gates?qubits=N — the palette, and with it `detail[].info`, which
        # is the per-gate reference card the Gates tab draws. Those cards reach
        # the UI inside the /api/explain response, so without this the tab was
        # the one piece of teaching content still empty with no backend.
        "gates": main.gates(qubits=qubits),
        # /api/concepts?qubits=N
        "concepts": main.concepts(qubits=qubits),
        # /api/circuits?qubits=N
        "circuits": main.circuits(qubits=qubits),
        # /api/circuits/{id}?qubits=N, keyed by id — the ids are upper case
        # already, and the route upper-cases what it is given, so a lookup on
        # `id.toUpperCase()` in the frontend matches the route's behaviour.
        "cases": {c["id"]: main.circuit_detail(c["id"], qubits=qubits) for c in cases},
    }


def serialise(doc: dict) -> str:
    """Stable text: sorted keys and real UTF-8, so a re-run with no content
    change produces no diff and the files stay readable in review."""
    return json.dumps(doc, ensure_ascii=False, indent=1, sort_keys=True) + "\n"


def main_(argv=None) -> int:
    # Paths and the banner carry non-cp1252 characters; a Windows console would
    # otherwise raise on them rather than print the report.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="verify the committed files are up to date, write nothing")
    args = ap.parse_args(argv)

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    stale = []

    print("QubitVista catalogue export — static fallback for the frontend\n")
    for qubits, path in FILES.items():
        text = serialise(build(qubits))
        doc = json.loads(text)
        counts = (f"{len(doc['gates']['gates'])} gate cards, "
                  f"{len(doc['concepts'])} concepts, "
                  f"{doc['circuits']['count']} circuits, "
                  f"{len(doc['cases'])} case documents")

        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else None
            ok = current == text
            if not ok:
                stale.append(path)
            print(f"  {qubits} qubit{'s' if qubits == 2 else ' '}   "
                  f"{'UP TO DATE' if ok else 'STALE'}   {path.name} — {counts}")
            continue

        path.write_text(text, encoding="utf-8")
        print(f"  {qubits} qubit{'s' if qubits == 2 else ' '}   "
              f"wrote {path.name}   {len(text) / 1024:.0f} kB — {counts}")

    print()
    if stale:
        print("STALE — re-run `python export_catalogue.py` and commit the result:")
        for p in stale:
            print(f"   x  {p}")
        return 1
    print("catalogue exported" if not args.check else "static catalogue is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main_())
